
---
- name: git module demo
  hosts: all
  become: true
  vars:
    repo: "https://github.com/ActuaryEmma/yolo"
    dest: "/home/emma/yolo"
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
  

    - name: checkout git repo
      git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
       


