apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-front
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: yolo
  template:
    metadata: 
      labels:
        app: yolo
    spec:
      containers:
        - name: clientcontainer
          image: actuaryemma/frontend:1
          ports: 
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-front
spec:
  type: LoadBalancer
  selector:
    app: yolo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http