# apiVersion: v1
# kind: Service
# metadata:
#  name: mongo
#  labels:
#    app: mongodb
# spec:
#  ports:
#  - port: 27017
#    targetPort: 27017
#  clusterIP: None
#  selector:
#    role: mongo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: Emma
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Emma
        ports:
        - containerPort: 27017
        command:
        - mongod
        - "--bind_ip_all"
        - "--auth"
        - "--replSet"
        - "rs0"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  type: ClusterIP


