apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-app
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: yolo-app
        component: back
    spec:
      containers:
        - name: yolo-backend
          image: actuaryemma/api:1
          ports: 
            - containerPort: 5000
          env: 
            - name: PORT
              value: "5000"
            - name: CONN_STR
              value: "$ATLAS_CONNECTION_STRING"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
  labels:
    app: yolo-app
    component: back
spec:
  type: LoadBalancer
  selector:
    component: back
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-front
  labels:
    app: yolo-app
    component: front
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: front
  template:
    metadata: 
      labels:
        app: yolo-app
        component: front
    spec:
      containers:
        - name: yolo-front
          image: actuaryemma/frontend:1
          ports: 
            - containerPort: 80
          env: 
            - name: BASE_URL
              value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-front
  labels:
    app: yolo-app
    component: front
spec:
  type: LoadBalancer
  selector:
    component: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http