apiVersion: v1
kind: PersistentVolume
metadata:
  name: yolo-pv-app
  labels:
    app: yolo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-actuary-yolo-default-pool-22d5e469-0nlr 
    fsType: ext4


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-pvc-app
  labels:
    app: yolo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
   
